# TCL File Generated by Component Editor 13.0sp1
# Tue Mar 29 15:12:45 CEST 2016
# DO NOT MODIFY


# 
# Barcode_scan "Barcode_scan" v1.0
#  2016.03.29.15:12:45
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Barcode_scan
# 
set_module_property DESCRIPTION ""
set_module_property NAME Barcode_scan
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MIPO
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Barcode_scan
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pixel_scan
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file pixel_scan.vhd VHDL PATH ../pixel_scan.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock_mm
set_interface_property s1 associatedReset reset_mm
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 8
add_interface_port s1 avs_s1_writedata writedata Input 8
add_interface_port s1 avs_s1_readdata readdata Output 8
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_st
set_interface_property avalon_streaming_sink associatedReset reset_st
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink ast_sink_ready ready Output 1
add_interface_port avalon_streaming_sink ast_sink_valid valid Input 1
add_interface_port avalon_streaming_sink ast_sink_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink ast_sink_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink ast_sink_data data Input 8


# 
# connection point clock_st
# 
add_interface clock_st clock end
set_interface_property clock_st clockRate 0
set_interface_property clock_st ENABLED true
set_interface_property clock_st EXPORT_OF ""
set_interface_property clock_st PORT_NAME_MAP ""
set_interface_property clock_st SVD_ADDRESS_GROUP ""

add_interface_port clock_st clk clk Input 1


# 
# connection point reset_st
# 
add_interface reset_st reset end
set_interface_property reset_st associatedClock clock_st
set_interface_property reset_st synchronousEdges DEASSERT
set_interface_property reset_st ENABLED true
set_interface_property reset_st EXPORT_OF ""
set_interface_property reset_st PORT_NAME_MAP ""
set_interface_property reset_st SVD_ADDRESS_GROUP ""

add_interface_port reset_st reset_n reset_n Input 1


# 
# connection point clock_mm
# 
add_interface clock_mm clock end
set_interface_property clock_mm clockRate 0
set_interface_property clock_mm ENABLED true
set_interface_property clock_mm EXPORT_OF ""
set_interface_property clock_mm PORT_NAME_MAP ""
set_interface_property clock_mm SVD_ADDRESS_GROUP ""

add_interface_port clock_mm avs_s1_clk clk Input 1


# 
# connection point reset_mm
# 
add_interface reset_mm reset end
set_interface_property reset_mm associatedClock clock_mm
set_interface_property reset_mm synchronousEdges DEASSERT
set_interface_property reset_mm ENABLED true
set_interface_property reset_mm EXPORT_OF ""
set_interface_property reset_mm PORT_NAME_MAP ""
set_interface_property reset_mm SVD_ADDRESS_GROUP ""

add_interface_port reset_mm avs_s1_reset_n reset_n Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_st
set_interface_property avalon_streaming_source associatedReset reset_st
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source ast_source_valid valid Output 1
add_interface_port avalon_streaming_source ast_source_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source ast_source_data data Output 8
add_interface_port avalon_streaming_source ast_source_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source ast_source_ready ready Input 1


# 
# connection point debug
# 
add_interface debug conduit end
set_interface_property debug associatedClock clock_mm
set_interface_property debug associatedReset ""
set_interface_property debug ENABLED true
set_interface_property debug EXPORT_OF ""
set_interface_property debug PORT_NAME_MAP ""
set_interface_property debug SVD_ADDRESS_GROUP ""

add_interface_port debug debug_state export Output 8


# 
# connection point restart
# 
add_interface restart conduit end
set_interface_property restart associatedClock clock_mm
set_interface_property restart associatedReset reset_mm
set_interface_property restart ENABLED true
set_interface_property restart EXPORT_OF ""
set_interface_property restart PORT_NAME_MAP ""
set_interface_property restart SVD_ADDRESS_GROUP ""

add_interface_port restart restart export Input 1

